Sprint 16
Alekse1Frolov/Tracker pull request #4
Opened 2024-12-12 22:37 UTC by Alekse1Frolov

Доброго времени суток!

Направляю на проверку мою работу к 16-му спринту. Заранее благодарю за обратную связь!

2024-12-13 11:30 UTC, Kirchberg commented
Когда работаешь с архитектурой MVVM (Model-View-ViewModel), важно хорошо структурировать проект, чтобы было удобно работать с кодом. Вот несколько советов, как стоит организовать проект:

1. Организация по фичам:
   - Разделяй проект на папки по основным фичам или модулям приложения, например, Authentication, UserProfile, Dashboard и так далее.
   - Каждая такая папка должна включать в себя все, что нужно для реализации этой фичи: модели, View и их ViewModel.
   - Это поможет легко ориентироваться в проекте и быстро находить нужный код.

2. Структура внутри папок фич:
   - Models: Здесь храним все модели данных, связанные с фичей. Они описывают структуру данных и обычно не содержат бизнес-логики.
   - ViewModels: В этой папке держим ViewModel — они содержат логику, подготавливая данные для отображения во View. 
   - Views: Здесь размещаем все, что связано с UI: контроллеры представлений, ячейки таблиц и другие UI-элементы. Их задача — отображать данные и взаимодействовать с пользователем.
   - Services/Networking (если нужно): Если фича требует работы с сетью, можно создать папку для сервисов внутри фичи. Это поможет держать все специфические запросы и логику работы с данными в одном месте.

3. Дополнительные моменты:
   - Если есть какие-то вспомогательные вещи, вроде утилит или расширений, их можно вынести в отдельные папки на уровне всего проекта, если они используются в нескольких фичах.
   - Если у тебя сложная навигация между частями приложения, подумай над добавлением Coordinators или Routers для управления переходами.

Правильная организация проекта — это ключ не только к удобной разработке, но и к легкой поддержке и развитию приложения, особенно если ты работаешь в команде. Надеюсь, эти советы помогут тебе!

2024-12-13 11:40 UTC, Kirchberg requested changes
⚠️ Критические замечания (это нужно исправить обязательно):

1. Не смог запустить проект, так как отсутствует файл с моделью базы данных. Необходимо удалить файл из проекта как Remove Reference и добавить снова, [см. скриншот проекта](https://ibb.co/1df1fFR).
2. Онбординг не соответствует макетам, нехватает индикатора текущей страницы, [см. скриншот сравнения симулятора с макетом](https://ibb.co/QbdQkCS).
3. Нельзя создать привычку или нерегулярное событие, так как при выборе категории не скрывается экран, можно только создать категорию, [см. видео](https://disk.yandex.ru/i/zD8p2GaVgmaJZQ).

Без исправлений этих пунктов, я не смогу принять у тебя работу. Если возникнут вопросы, обязательно задавай их Наставнику!

2024-12-15 22:08 UTC, Alekse1Frolov commented
Кирилл, привет! Большое спасибо за обратную связь! Я заново добавил файл с моделью БД, добавил отображение pageControl на экранах онбординга и разобрался с переходом с экрана со списком категорий на экран создания трекера - у меня не так как в требованиях переход был реализован. Также распределил файлы по папкам. В общем вроде получилось отработать все твои замечания) Посмотри, пожалуйста

2024-12-16 07:58 UTC, Kirchberg approved these changes
Отлично получилось, распределение по папкам огонь, молодец 🔥

Не забудь вмерджить пул-реквест в основную ветку.
Успехов в следующем задании!

2024-12-16 19:50 UTC, merged